"""Engine facade (Phase 3): re-exports the full engine surface.

`from reportforge.engine import X` (mcp_server, cli) and
`engine.X` attribute access (tests, including monkeypatching the
stub-able internals) behave exactly as when engine was one module.
"""

from __future__ import annotations

# NOTE (Phase 3): import order matters — `sections` defines
# `_section_op_errors`, which `registry`/`release`/`cover` apply as a
# decorator at THEIR import time (via `_E.`). Keep `sections` before them.
from reportforge.engine._impl import (  # noqa: F401
    BRAND_TOKENS,
    EXEC_OUTPUT_TAIL,
    FACT_HISTORY_CAP,
    ILLUSTRATIVE_MARKERS,
    MCP_TOOL_NAMES_FALLBACK,
    PUBLIC_FORMATS,
    QUANTFLOW_PLOTLY_THEMES,
    RENDER_LOG_TAIL_CHARS,
    REPORTS_DIR,
    REQUIRED_EVIDENCE,
    REQUIRED_SECTIONS,
    RenderResult,
    _ASOF_RE,
    _BARE_NUM_RE,
    _BIB_YEAR_RE,
    _BUNDLE_FORMATS,
    _CODE_SPAN_RE,
    _COLUMN_PAGE_RE,
    _COVER_BLOCKS,
    _DATE_FM_RE,
    _EDITORIAL_TEMPLATES,
    _FIGANCHOR_RE,
    _FIGEMBED_RE,
    _FIGREF_RE,
    _HEDGE_RE,
    _HTML_COMMENT_RE,
    _LEDGER_TEMPLATES,
    _METRIC_WORDS,
    _MONEY_RE,
    _NCOL_RE,
    _PCT_RE,
    _PORTFOLIO_TEMPLATES,
    _PORTFOLIO_TO_QUANTFLOW_TEMPLATE,
    _PRICEISH_RE,
    _PROFILE_AXES,
    _PROFILE_BRANDS,
    _PROFILE_LAYOUTS,
    _PROFILE_OUTPUTS,
    _PROFILE_OVERRIDABLE,
    _PROFILE_POLICIES,
    _PROFILE_THEMES,
    _ROLLFORWARD_SKIP,
    _SIGN_NEG_RE,
    _SIGN_POS_RE,
    _SPOT_WORDS_RE,
    _SRC_CITE_RE,
    _STATUS_FORMAT_IDS,
    _TARGET_PHRASE_RE,
    _TARGET_WORD_RE,
    _TEMPLATE_DEFAULT_ACCENTS,
    _TICKER_RE,
    _TICKER_STOP,
    _WIDTH_PCT_RE,
    _WINDOW_WORDS,
    _chromium_binary,
    _declares_typst_format,
    _default_reference_docx,
    _engine_charts_violation,
    _ensure_reportforge_kernel,
    _figure_template_is_stock_default,
    _load_or_import,
    _non_engine_charts,
    _output_dir_of,
    _pdf_page_count,
    _project_is_light,
    _project_lock,
    _project_root_of,
    _project_template_name,
    _public_format_name,
    _quarto_tools_dir,
    _quarto_version,
    _render_pdf_web,
    _run_figure_lint,
    _tool_version,
    _toolchain_stamp,
    _tpl,
    _venv_python,
    _white_paper_charts,
    render_report,
)
from reportforge.engine.scaffold import (  # noqa: F401
    _drop_yaml_block,
    _frontmatter_flag,
    _metric_yaml,
    _normalize_key_points,
    _normalize_kpis,
    _normalize_scenarios,
    _profile_for_template,
    _profile_matrix_error,
    _scenario_yaml,
    _set_frontmatter_flag,
    _str_list_yaml,
    _write_scaffold_manifest,
    _yaml_scalar,
    list_templates,
    scaffold_report,
    template_version,
)
from reportforge.engine.readiness import (  # noqa: F401
    _body_text,
    _cover_number,
    _cover_numeric_candidates,
    _cover_values_match,
    _extract_quantities,
    _figure_layout_kind,
    _frontmatter_dict,
    _governor_kind,
    _header_cell_for,
    _is_table_row,
    _issue,
    _label_tokens,
    _missing_work_summary,
    _num_value,
    _pipe_tables,
    _readiness_editorial,
    _readiness_evidence,
    _readiness_evidence_coverage,
    _readiness_layout_policies,
    _readiness_numerical,
    _readiness_presentation,
    _readiness_structure,
    _same_key,
    _scenario_pairs,
    _section_for_line,
    _stated_weighted_return,
    _strip_code_spans_and_comments,
    check_readiness,
    record_review,
)
from reportforge.engine.sections import (  # noqa: F401
    _append_locked,
    _check_expected,
    _commit_qmd_change,
    _find_span,
    _first_heading_id,
    _project_root_or_error,
    _section_op_errors,
    _section_spans,
    _set_frontmatter_description,
    _stale_response,
    _write_qmd_atomic,
    append_section,
    delete_section,
    get_section,
    move_section,
    replace_section,
    write_report_body,
)
from reportforge.engine.registry import (  # noqa: F401
    _bibtex_escape,
    _bibtex_escape_url,
    _check_registry_links,
    _ensure_bibliography,
    _exhibit_anchors,
    _parse_asof,
    _register_exhibit_locked,
    _register_fact_locked,
    _source_to_bibtex,
    register_exhibit,
    register_fact,
    register_source,
    update_fact,
)
from reportforge.engine.preview import (  # noqa: F401
    _build_contact_sheet,
    _describe_or_skip,
    _file_descriptor,
    _numbered_pages,
    _page_sort_key,
    render_preview,
)
from reportforge.engine.cover import (  # noqa: F401
    _cover_field_fact_id,
    _yaml_cover_scalar,
    derive_cover,
)
from reportforge.engine.publish import (  # noqa: F401
    _translate_sandbox_path,
    publish_report,
)
from reportforge.engine.charts import (  # noqa: F401
    _anchor_chart_output,
    _apply_quantflow_plotly_template,
    _slugify_exhibit_id,
    save_asset,
    save_chart,
    tokens_for,
    tokens_for_keys,
)
from reportforge.engine.status import (  # noqa: F401
    _manifest_view,
    _mcp_tool_names,
    _mime_for_name,
    _render_state_registry_version,
    _render_state_revision,
    _status_artifacts,
    open_report,
    project_status,
    read_project_file,
    reportforge_capabilities,
)
from reportforge.engine.release import (  # noqa: F401
    _bundle_artifact_id,
    _export_release_locked,
    _read_release_record,
    _registry_content_hash,
    _release_inputs,
    _release_summary,
    _write_release_record,
    export_release,
    freeze_release,
    rollforward_report,
)
from reportforge.engine.exec_env import (  # noqa: F401
    _diff_snapshot,
    _exec_enabled,
    _project_optional,
    _resolve_project_root,
    _snapshot_project,
    _tail,
    run_code,
    run_file,
)
from reportforge.engine._impl import (  # noqa: F401
    CHROMIUM_PRINT_TIMEOUT_S,
    QUARTO_TIMEOUT_S,
    Template,
    _REPORTFORGE_VERSION,
    _rlint,
    _rprobe,
    _rquarto,
    dataclass,
    fcntl,
    sys,
)
from reportforge.engine.charts import (  # noqa: F401
    base64,
)
from reportforge.engine.exec_env import (  # noqa: F401
    Path,
    _rerrors,
    _rinterpreters,
    _rtoolchain,
    annotations,
    os,
    time,
)
from reportforge.engine.preview import (  # noqa: F401
    _rpoppler,
)
from reportforge.engine.release import (  # noqa: F401
    date,
    datetime,
    hashlib,
    json,
    manifest_mod,
    re,
    shutil,
)
from reportforge.engine.scaffold import (  # noqa: F401
    html_escape,
)
from reportforge.engine.sections import (  # noqa: F401
    functools,
    tempfile,
)
from reportforge.engine.status import (  # noqa: F401
    templates,
    yaml,
)
