#!/usr/bin/env python3
"""Derive Cyan Ledger report templates from the portfolio templates.

The LEDGER_DARK_* / LEDGER_LIGHT_* constants in
src/reportforge/templates.py are mechanical derivations of the
PORTFOLIO_* ones: same studio structure (cover infographics, showtable,
two-column body, Exhibit numbering), Cyan Ledger palette + type.

Source system: Kizo07.github.io `fusion/cyan-ledger` (v4: electric cyan
#08bfff x ledger gold #e3ac55 dark / #8f621f light, Space Grotesk / Inter /
IBM Plex Mono, midnight dark + ice light).

Chart-facing hexes mirror alpha_engine.viz LEDGER_DARK/LEDGER_LIGHT
(canonical); page tokens follow so charts stay pixel-matched to pages.

Usage: python3 scripts/derive_ledger_templates.py [--check]
  --check: exit 1 if templates.py is missing or stale LEDGER blocks.
Idempotent: refreshes (rewrites) the derived section in place.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TPL = ROOT / "src" / "reportforge" / "templates.py"

# Portfolio source constants, in canonical derivation-output order.
SOURCES = [
    "PORTFOLIO_DARK_TYPT_TEMPLATE",
    "PORTFOLIO_DARK_TYPT_SHOW",
    "PORTFOLIO_DARK_STYLES_EXTRA",
    "PORTFOLIO_DARK_BRAND_YML",
    "PORTFOLIO_LIGHT_TYPT_TEMPLATE",
    "PORTFOLIO_LIGHT_TYPT_SHOW",
    "PORTFOLIO_LIGHT_STYLES_EXTRA",
    "PORTFOLIO_LIGHT_BRAND_YML",
]

BANNER = (
    "# --- Cyan Ledger variants (derived) --------------------------------------------\n"
    "# Generated by scripts/derive_ledger_templates.py from the\n"
    "# PORTFOLIO_* constants above. Do not hand-edit; re-run the\n"
    "# generator after portfolio changes.\n"
)

_ASSIGN_RE = re.compile(r"^([A-Z_]+) = (r?)\"\"\"")

DARK_MAP = [
    ("#d9a54e", "#e3ac55"),  # ledger gold (dark)
    ("#56cfc4", "#08bfff"),  # ledger cyan
    ("#10151d", "#0b1220"),  # midnight panel (== alpha plot_bg)
    ("#e7eaf0", "#e8eef4"),  # ice ink (== alpha font)
    ("#9aa4b2", "#93a3b8"),  # ledger muted (== alpha muted)
    ("#0a0d12", "#060a12"),  # midnight paper
    ("#1e2632", "#16202e"),  # hairline (== alpha grid)
    ("#151b25", "#1d2b3f"),  # panel-2 (== alpha border)
    ("#1b2230", "#101a29"),
    ("#0d1219", "#080d16"),
    ("#1d1a10", "#161206"),
    ("#7d8795", "#6f7f8f"),
    ("#3ecf8e", "#34d399"),  # ledger green (== alpha positive)
    ("#ef6a6a", "#f87171"),  # ledger red (== alpha negative)
    # Font stacks: composite rules first so bare-token renames below
    # can never double-apply inside an already-rewritten stack.
    ('"Fraunces", Georgia, serif', '"Space Grotesk", sans-serif'),
    ("Fraunces, Georgia, serif", '"Space Grotesk", sans-serif'),
    ('"IBM Plex Mono", "JetBrains Mono", monospace', '"IBM Plex Mono", monospace'),
    ("Georgia", "Space Grotesk"),  # Typst display font (local-only fallback)
    ("Fraunces", "Space Grotesk"),
    ("JetBrains Mono", "IBM Plex Mono"),
    ("PORTFOLIO_DARK", "LEDGER_DARK"),
    ("portfolio-dark", "ledger-dark"),
    ("portfolio_dark", "ledger_dark"),
    ("Portfolio Dark", "Ledger Dark"),
    ("PORTFOLIO REPORT", "LEDGER REPORT"),
]

LIGHT_MAP = [
    ("#14756c", "#009ed9"),  # scheme-safe cyan
    ("#ebe3d2", "#e7edf2"),  # ice panel
    ("#362e21", "#1b2634"),  # slate ink
    ("#6d6250", "#63798a"),  # muted (== alpha muted)
    ("#e5ddcc", "#eef3f6"),  # ice paper
    ("#d3c8b0", "#d5dde4"),  # hairline (== alpha grid)
    ("#e0d7c4", "#dde5ec"),
    ("#d9cba6", "#d3dde6"),
    ("#e0d4ba", "#d8e1e9"),
    ("#e2d3ac", "#d5dee7"),
    ("#efe4cb", "#e9eff4"),
    ("#2c6e4a", "#1f8a4c"),  # positive (== alpha)
    ("#a44a44", "#cf4444"),  # negative (== alpha)
    # Font stacks: composite rules first (see DARK_MAP).
    ('"Fraunces", Georgia, serif', '"Space Grotesk", sans-serif'),
    ("Fraunces, Georgia, serif", '"Space Grotesk", sans-serif'),
    ('"IBM Plex Mono", "JetBrains Mono", monospace', '"IBM Plex Mono", monospace'),
    ("Georgia", "Space Grotesk"),
    ("Fraunces", "Space Grotesk"),
    ("JetBrains Mono", "IBM Plex Mono"),
    ("PORTFOLIO_LIGHT", "LEDGER_LIGHT"),
    ("portfolio-light", "ledger-light"),
    ("portfolio_light", "ledger_light"),
    ("Portfolio Light", "Ledger Light"),
    ("PORTFOLIO REPORT", "LEDGER REPORT"),
]


def derive(src: str, mapping: list[tuple[str, str]]) -> str:
    # Tokens are inventoried across the whole template family; individual
    # blocks contain subsets — absent tokens are skipped, not errors.
    for old, new in mapping:
        if old != new and old in src:
            src = src.replace(old, new)
    return src


def _block(text: str, name: str) -> str:
    """Exact source lines of a template constant: assignment line through
    its closing \"\"\" delimiter, name-anchored (immune to line drift)."""
    lines = text.splitlines(keepends=True)
    starts = [i for i, line in enumerate(lines) if line.startswith(f"{name} = ")]
    if len(starts) != 1:
        raise AssertionError(f"{name}: expected exactly one assignment, found {len(starts)}")
    a = starts[0]
    for b in range(a + 1, len(lines)):
        if lines[b].rstrip("\n") == '"""':
            return "".join(lines[a : b + 1])
    raise AssertionError(f"{name}: unterminated triple-quoted literal")


def _ledger_region(text: str) -> tuple[int, int] | None:
    """(start, end) line indexes of the derived section, banner through the
    last LEDGER_* block's closing delimiter; None when absent."""
    lines = text.splitlines(keepends=True)
    banners = [i for i, line in enumerate(lines)
               if line.startswith("# --- Cyan Ledger variants (derived)")]
    assigns = [i for i, line in enumerate(lines)
               if re.match(r"^LEDGER_(DARK|LIGHT)_[A-Z_]+ = ", line)]
    if not banners and not assigns:
        return None
    start = min(banners + assigns)
    # End = closing delimiter line of the last LEDGER assignment.
    last = max(assigns)
    for b in range(last + 1, len(lines)):
        if lines[b].rstrip("\n") == '"""':
            return start, b
    raise AssertionError("LEDGER section: unterminated final block")


def build() -> dict[str, str]:
    text = TPL.read_text()
    out: dict[str, str] = {}
    for const in SOURCES:
        tag = const.replace("PORTFOLIO_DARK", "LEDGER_DARK").replace(
            "PORTFOLIO_LIGHT", "LEDGER_LIGHT")
        mapping = DARK_MAP if const.startswith("PORTFOLIO_DARK") else LIGHT_MAP
        out[tag] = derive(_block(text, const), mapping)
    # Fix derived header comments to name the ledger source.
    out["LEDGER_DARK_TYPT_TEMPLATE"] = out["LEDGER_DARK_TYPT_TEMPLATE"].replace(
        '// report-forge "ledger-dark" — studio structure, portfolio dark palette',
        '// report-forge "ledger-dark" — studio structure, Cyan Ledger midnight palette '
        "(derived; see scripts/derive_ledger_templates.py)",
        1,
    )
    out["LEDGER_LIGHT_TYPT_TEMPLATE"] = out["LEDGER_LIGHT_TYPT_TEMPLATE"].replace(
        '// report-forge "ledger-light" — studio structure, portfolio light palette',
        '// report-forge "ledger-light" — studio structure, Cyan Ledger ice palette '
        "(derived; see scripts/derive_ledger_templates.py)",
        1,
    )
    return out


def render(blocks: dict[str, str]) -> str:
    """Full derived-section text, byte-stable: banner + blank-line-separated
    blocks, matching the original append format."""
    parts = [BANNER]
    for key in blocks:
        parts.append("\n" + blocks[key].rstrip("\n") + "\n")
    return "".join(parts)


def main() -> int:
    text = TPL.read_text()
    blocks = build()
    fresh = render(blocks)
    region = _ledger_region(text)

    if "--check" in sys.argv:
        if region is None:
            print("derive_ledger: LEDGER section missing — run the generator")
            return 1
        lines = text.splitlines(keepends=True)
        current = "".join(lines[region[0] : region[1] + 1])
        if current != fresh:
            print("derive_ledger: LEDGER blocks stale — re-run the generator")
            return 1
        print("derive_ledger: LEDGER blocks present and fresh")
        return 0

    if region is None:
        TPL.write_text(text.rstrip("\n") + "\n\n\n" + fresh)
        print(f"derive_ledger: appended {len(blocks)} blocks")
        return 0

    lines = text.splitlines(keepends=True)
    head = "".join(lines[: region[0]]).rstrip("\n")
    tail_lines = lines[region[1] + 1 :]
    tail = "".join(tail_lines) if "".join(tail_lines).strip() else ""
    TPL.write_text(head + "\n\n\n" + fresh + tail)
    print(f"derive_ledger: refreshed {len(blocks)} blocks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
